name: CI

# 1
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [production]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
#2
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://api.drs.scidar.org
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build container image
        run: docker build -t ${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}:$(echo $GITHUB_SHA | head -c7) .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Remove all old images
        run: if [ ! -z "$(doctl registry repository list | grep "${{ vars.IMAGE_NAME }}")" ]; then doctl registry repository delete-manifest ${{ vars.IMAGE_NAME }} $(doctl registry repository list-tags ${{ vars.IMAGE_NAME }} | grep -o "sha.*") --force; else echo "No repository"; fi

      - name: Push image to DigitalOcean Container Registry
        run: docker push ${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}:$(echo $GITHUB_SHA | head -c7)
